modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="werefish"
version="1.0.0"
displayName="Werefish"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="0398313, MCreator"

[[dependencies.werefish]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"

[[dependencies.werefish]]
    modId="forge"
    mandatory=true
    versionRange="[36.1.0]"
    ordering="NONE"
    side="BOTH"



